# This is a basic workflow to build LaTeX files
name: Build TVY-POS LaTeX document

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one job
jobs:
  # This workflow contains one job called "build_latex"
  build_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a LaTeX build
      - name: Compile TVY-POS LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tvy-pos.tex
      # Uploads builded files
      - name: Upload document
        uses: actions/upload-artifact@v2
        with:
          name: TVY-POS
          path: tvy-pos.pdf